# Copyright (C) Pointon Software - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Ben Ziv <pointonsoftware@gmail.com>, September 2020

name: weekly

# Run schedule every Friday 2am UTC
# PH time     - 10am Friday
# Canada time - 10pm Thrusday

on:
  schedule:
  - cron: "0 3 * * 5"

jobs:
  windows:
    name:  Weekly Windows Build
    runs-on: windows-latest

    steps:
    - name: Install
      uses: msys2/setup-msys2@v2
      with:
        install: cmake mingw-w64-x86_64-gcc

    - name: Code checkout
      uses: actions/checkout@v2
      with:
        ref: 'master'
        submodules: recursive

    - name: Build
      shell: bash
      run  : ./clean_build.sh

    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        name: binary-artifact
        path: build/bin/

    - name: Upload Libraries
      uses: actions/upload-artifact@v2
      with:
        name: library-artifact
        path: |
          build/lib/libdatamanager.a
          build/lib/libentity.a
          build/lib/libutility.a